-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgIuQxVnrsc1HHBkHE
TD2cMqGo55OfiBLE5KW+7wwTK8ygCgYIKoZIzj0DAQehRANCAASlqz67wNOBmO1f
P3dz7LtSr8kGV3MxjNhBXvZ5tS7sH+ExlhXyEfVWYaMRXgvIAHA//7lw+aXzPRwp
uX2HtdT3
-----END PRIVATE KEY-----