#!/usr/bin/env sh

# bar settings
yabai -m config status_bar off
yabai -m config status_bar_text_font "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color 0xff202020
yabai -m config status_bar_foreground_color 0xffa8a8a8
yabai -m config status_bar_space_icon_strip I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip  
yabai -m config status_bar_space_icon 
yabai -m config status_bar_clock_icon 

# global settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse off
yabai -m config window_placement second_child
yabai -m config window_topmost on
yabai -m config window_opacity on
yabai -m config window_shadow on
yabai -m config window_border off
yabai -m config window_border_width 3
yabai -m config window_border_placement exterior
yabai -m config active_window_border_color 0xff4db5bd
yabai -m config normal_window_border_color 0xff505050
yabai -m config insert_window_border_color 0xffd75f5f
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 00
yabai -m config bottom_padding 00
yabai -m config left_padding 00
yabai -m config right_padding 00
yabai -m config window_gap 00

##########################################################################################
# Default yabai to off for everything (so we can explicitly whitelist apps for yabai)
#yabai -m rule --add app=".*" manage=off
yabai -m rule --add app!="^(Google Chrome|Safari|Brave|Vivaldi|Slack|iTerm2|Finder)$" manage=off

##########################################################################################
# Emacs Settings

#yabai -m rule --add app="Emacs" title="^$" manage=off
#yabai -m rule --add app="Emacs" title!="^$" manage=on #ivy-posframe windows currently have an empty title
#yabai -m rule --add app="Emacs" title="emacs-client" manage=on

#yabai -m rule --add app="Emacs" title=" *Minibuf-2* .*" manage=off
yabai -m rule --add app="Emacs" title="doom-capture.*" manage=off sticky=on grid=20:20:4:4:10:12
yabai -m rule --add app="Emacs" title=".*Doom\ Emacs" manage=on

#yabai -m rule --add app="Emacs" title="^\*.*\*$" manage=off
#yabai -m rule --add app="Emacs" title="^Ediff$" manage=off

yabai -m rule --add app="Emacs" title="^Ediff" manage=off
yabai -m rule --add app="Emacs" title="^\*ediff-merge" manage=off layer=above
yabai -m rule --add app="Emacs" title=".*LOWER.*" manage=off layer=above
yabai -m rule --add app="Emacs" title=".*UPPER.*" manage=off layer=above

#yabai -m rule --add app="Emacs" title="^org-capture" manage=off sticky=on grid=20:20:6:8:8:6
#yabai -m rule --add app="Emacs" title="^ivy-posframe*" manage=off
#yabai -m rule --add app="Emacs" title="emacs \(main frame\)" manage=on
#yabai -m rule --add app="Emacs" title="emacs-client" manage=on

# grid-layout docs --> rows:cols:left:top:width:height

#yabai -m rule --add app="Finder" title=Copy manage=off
#yabai -m rule --add --label "App Store" --state float

##########################################################################################
# OSX App Settings

#yabai -m rule --add app="Safari" manage=on

#yabai -m rule --add app="iStat Menus" manage=on
#
#yabai -m rule --add app="Things" title!="^(Quick Entry|General|Things Cloud|Reminders|Calendar)$" manage=on
#yabai -m rule --add app="Bear" title="Bear" manage=on
#yabai -m rule --add app="1Password 7" manage=off sticky=on grid=40:40:4:4:30:32
#yabai -m rule --add app="System Preferences" manage=off grid=40:40:15:12:6:8
#yabai -m rule --add app="Deliveries" manage=off sticky=on grid=20:20:3:2:14:16
#yabai -m rule --add app="Podcasts" manage=off sticky=on grid=20:20:3:2:14:16
#
##yabai -m rule --add app="Music" manage=off #grid=20:20:3:2:14:16
#yabai -m rule --add app="Music" title="MiniPlayer" manage=on sticky=off
#
yabai -m rule --add app="TIDAL" title="^TIDAL$" manage=on                               #grid=20:20:2:2:16:16

yabai -m rule --add app="^Fantastical$" title="^Fantastical$" manage=on #grid=20:20:2:2:16:16
yabai -m rule --add app="^Fantastical Helper$" manage=off border=off
yabai -m rule --add app="Slack" manage=on #grid=20:20:2:2:16:16
yabai -m rule --add app="^Obsidian$" manage=on #grid=20:20:2:2:16:16
yabai -m rule --add app="^zoom.us$" title="^Zoom Meeting$" manage=on #grid=20:20:2:2:16:16
#yabai -m rule --add app="OmniFocus" manage=on #grid=20:20:2:2:16:16

yabai -m rule --add app="Emacs" title="client-frame" manage=on
yabai -m rule --add app="Emacs" title="server-frame" manage=off space=1
yabai -m rule --add app="AWS VPN Client" title="AWS VPN Client" manage=off space=1

##yabai -m rule --add app="Discord" manage=off sticky=on grid=40:40:4:4:30:32
##yabai -m rule --add app="Slack" manage=off sticky=on grid=10:10:2:1:6:8
#
#yabai -m rule --add app="Brave" title="^Pinboard" manage=off
#
#yabai -m rule --add app="Fantastical" manage=off

echo "yabai configuration loaded.."
