[core]
restore_state = false

[audio]
output = autoaudiosink

[http]
enabled = true
hostname = 127.0.0.1
port = 6681

[tidal]
enabled = true
quality = LOSSLESS
auth_method = OAUTH
login_server_port = 8989
login_method = AUTO
