#!/usr/bin/osascript
display notification "Restarting Server..." with title "Emacs"
tell application "Terminal"
	do shell script "open -nF /Applications/Emacs-NS.app"
end tell
#tell application "System Events"
#	repeat until window "Daemon Frame" of process "Emacs" exists
#	end repeat
#	display notification "Server Ready!" with title "Emacs"
#end tell
