#!/opt/homebrew/bin/fish

#require 'json'

# query current focused desktop
#windows_on_desktop = JSON.parse(`yabai -m query --windows --space`) 
set windows_query (yabai -m query --windows --space)
#echo $windows_query | jq -r '.[]'



#for win in windows_on_desktop
#  `yabai -m window #{win["id"]} --close`
#end
for window in (echo $windows_query | jq -c '.[]')
  set window_id (echo $window | jq '.id')
  yabai -m window $window_id --close
end

set PREV_SPACE_INDEX (yabai -m query --spaces --space prev | jq '.index')
set CURR_SPACE_INDEX (yabai -m query --spaces --space | jq '.index')

yabai -m space --focus $PREV_SPACE_INDEX
yabai -m space --destroy $CURR_SPACE_INDEX

