#!/opt/homebrew/bin/fish

#set PREV_SPACE_INDEX (yabai -m query --spaces --space prev | jq '.index')
set CURR_SPACE_INDEX (yabai -m query --spaces --space | jq '.index')

if test $CURR_SPACE_INDEX -le 1
  echo "cannot delete first space. exiting..." 
  exit 
end
set NEXT_LOWEST_SPACE (math $CURR_SPACE_INDEX - 1)

set windows_query (yabai -m query --windows --space)

for window in (echo $windows_query | jq -c '.[]')
  set window_id (echo $window | jq '.id')
  yabai -m window $window_id --close
end


yabai -m space --focus $NEXT_LOWEST_SPACE
yabai -m space --destroy $CURR_SPACE_INDEX

