# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


format = "$time$all$character"

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[cmd_duration]
show_notifications = true
min_time_to_notify = 10_000

[line_break]
disabled = false

[time]
disabled = true
format ="[$time -]($style) "

[git_branch]
symbol = " "
format = '[$symbol$branch]($style) '

[git_status]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
symbol = "󰏗 "
disabled = true

# aws package config
[aws]
disabled = false
symbol = " "
format = '[$symbol($profile )]($style)'

[terraform]
disabled = true

[gcloud]
disabled = true

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[golang]
symbol = " "

[memory_usage]
disabled = true
symbol = "󰍛 "

[nodejs]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
Emscripten = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

