#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  00
yabai -m config bottom_padding               00
yabai -m config left_padding                 00
yabai -m config right_padding                00
yabai -m config window_gap                   00

##########################################################################################
# Emacs Settings

yabai -m rule --add app="Emacs" manage=on 

#yabai -m rule --add app="Emacs" title="main-frame" manage=on 
#yabai -m rule --add app="Emacs" title="^org-capture$" manage=off sticky=on grid=20:20:7:8:6:4
#yabai -m rule --add app="Emacs" title="^ivy-posframe*" manage=off 
#yabai -m rule --add app="Emacs" title="emacs-client" manage=on 
#yabai -m rule --add app="Emacs" title="inbox-capture-popup" sticky=on float=on


# grid-layout docs --> rows:cols:left:top:width:height

#yabai -m rule --add app="Finder" title=Copy manage=off 
#yabai -m rule --add --label "App Store" --state float
yabai -m rule --add --label "Fantastical" manage=on
yabai -m rule --add app="1Password 7" manage=off sticky=on grid=40:40:4:4:30:32
yabai -m rule --add app="NordVPN" manage=off sticky=on grid=20:20:4:2:12:14
yabai -m rule --add app="System Preferences" manage=off grid=40:40:15:12:6:8
#yabai -m rule --add app="iTunes" manage=off grid=20:20:3:2:14:16
yabai -m rule --add app="Spotify" manage=off sticky=on grid=20:20:3:1:14:18
yabai -m rule --add app="TIDAL" manage=off sticky=on #grid=20:20:3:1:14:18
#yabai -m rule --add app="Messages" manage=off sticky=on grid=20:20:4:4:10:12
#yabai -m rule --add app="Discord" manage=off sticky=on grid=40:40:4:4:30:32
#yabai -m rule --add app="Slack" manage=off sticky=on grid=10:10:2:1:6:8

echo "yabai configuration loaded.."
