""""""""""""""""""""settings for vundle (copied from github.com/gmarik/vundle)""""""""""""""""""
set nocompatible              " be iMproved, required
filetype off                  " required

"" set the runtime path to include Vundle and initialize
"set rtp+=~/.vim/bundle/Vundle.vim
"call vundle#begin()
"" alternatively, pass a path where Vundle should install plugins
""call vundle#begin('~/some/path/here')
"
"" let Vundle manage Vundle, required
"Plugin 'gmarik/Vundle.vim'
"Plugin 'flazz/vim-colorschemes'
""Plugin 'scrooloose/syntastic'
"Plugin 'scrooloose/nerdtree'
""Plugin 'Valloric/YouCompleteMe'
"Plugin 'tpope/vim-fugitive'
"Plugin 'Lokaltog/vim-easymotion'
"
""markdown syntax coloring and such
"Plugin 'tpope/vim-markdown'
"
""ctrl-[h,j,k,] nav of splits
"Bundle 'christoomey/vim-tmux-navigator'
"
""Automatically causes vim to reload files which have been written on disk but
""not modified in the buffer since the last write from vim
"Bundle 'djoshea/vim-autoread'

"" The following are examples of different formats supported.
"" Keep Plugin commands between vundle#begin/end.
"" plugin on GitHub repo
"Plugin 'tpope/vim-fugitive'
"" plugin from http://vim-scripts.org/vim/scripts.html
"Plugin 'L9'
"" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
"" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
"" The sparkup vim script is in a subdirectory of this repo called vim.
"" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
"" Avoid a name conflict with L9
"Plugin 'user/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList          - list configured plugins
" :PluginInstall(!)    - install (update) plugins
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused plugins
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

""""""""""""""""""""""""""""""personal vim settings"""""""""""""""""""""""""""""""""""""""""

"stuff for ruby syntax (put in ftplugin later)
set expandtab
set tabstop=2 shiftwidth=2 softtabstop=2
set autoindent

"NERDTree plugin configurations
:command DirTree :NERDTreeToggle
 let NERDTreeShowLineNumbers=1 

"syntax highlighing
syntax on
colorscheme one

"open new split panes to the right and bottom
set splitbelow
set splitright

"map W to w, Q to q, and such to avoid tripping up when doing wq
:command WQ wq
:command Wq wq
:command W w
:command Q q

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>


"show line numbers
set nu

"all yy, dd, actions will copy to system clipboard
set clipboard=unnamed

"easymotion key mappings
let g:EasyMotion_leader_key = '<Leader>'
let mapleader = 's' 

"remove the escape key delay
set noesckeys
set timeoutlen=1000 ttimeoutlen=0

"link vim yanks and puts with the OSX clipbaord (only works with macvim i
"think)
set clipboard=unnamed
