#!/usr/bin/env sh

#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#sudo yabai --load-sa

# global settings
#yabai -m config mouse_follows_focus on
#yabai -m config focus_follows_mouse off
#yabai -m config window_placement second_child
#yabai -m config window_topmost on
#yabai -m config window_opacity on
#yabai -m config window_shadow on
#yabai -m config window_border off
#yabai -m config window_border_width 3
#yabai -m config active_window_border_color 0xff4db5bd
#yabai -m config normal_window_border_color 0xff505050
#yabai -m config active_window_opacity 1.0
#yabai -m config normal_window_opacity 1.0
#yabai -m config split_ratio 0.50
#yabai -m config auto_balance off
#yabai -m config mouse_modifier fn
#yabai -m config mouse_action1 move
#yabai -m config mouse_action2 resize

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 00
yabai -m config bottom_padding 00
yabai -m config left_padding 00
yabai -m config right_padding 00
yabai -m config window_gap 00

##########################################################################################
# Default yabai to off for everything (so we can explicitly whitelist apps for yabai)
yabai -m rule --add app=".*" manage=off

##########################################################################################
# OSX App Settings

yabai -m rule --add app="AWS VPN Client" title="AWS VPN Client" manage=off

yabai -m rule --add app="TIDAL" title="^TIDAL$" manage=off
yabai -m rule --add app="Music" title="Music" manage=off

yabai -m rule --add app="^Fantastical$" title="^Fantastical$" manage=off
#yabai -m rule --add app="^Fantastical Helper$" manage=off border=off

yabai -m rule --add app="Obsidian" role="AXWindow" subrole="AXStandardWindow" manage=on

yabai -m rule --add app="Firefox" role="AXWindow" subrole="AXStandardWindow" manage=on
yabai -m rule --add app="Hyper" title="Hyper" role="AXWindow" subrole="AXStandardWindow" manage=on
yabai -m rule --add app="Safari" role="AXWindow" subrole="AXStandardWindow" manage=on
yabai -m rule --add app="Arc" title=".+" role="AXWindow" subrole="AXStandardWindow" manage=on
yabai -m rule --add app="Thorium" title=".+" role="AXWindow" subrole="AXStandardWindow" manage=on

yabai -m rule --add app="Xcode" role="AXWindow" subrole="AXStandardWindow" manage=on
yabai -m rule --add app="Code" role="AXWindow" subrole="AXStandardWindow" manage=on layer=below

yabai -m rule --add app="GoodTask" title="GoodTask"  role="AXWindow" subrole="AXStandardWindow" manage=on
yabai -m rule --add app="OmniFocus" role="AXWindow" subrole="AXStandardWindow" manage=on

echo "yabai configuration loaded.."
