version: '3'

# vars:
#   SITE_PACKAGES: 
#     sh: pdm run python -c "import site; print(site.getsitepackages()[0])"

tasks:
      
  build:
    cmds:
      - pdm build

  install:
    cmds:
      - pipx install dist/*.whl
      
  uninstall: 
    cmds:
      - cmd: rm ~/.local/bin/chrome-gc
        ignore_error: true
      - cmd: rm ~/.local/bin/awsc
        ignore_error: true

  chrome:
    cmds: 
      - /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --no-first-run --no-default-browser-check --user-data-dir=./chrome_userdata_dirs/dir1


  clean: 
    cmds:
      - cmd: rm -rf dist
        ignore_error: true

      
