#!/bin/bash

set -e

# If emacs isn't running, we start a daemon
if ! emacsclient -s $1 --suppress-output --eval nil; then
  emacs --daemon=$1
fi

emacsclient -a "" \
  -s $1 \
  -c \
  -F "((name . \"Doom Emacs: $1\") (display . \":0\"))" \
  -e '(progn (+get-create-shell "~/") (+focus-this-frame))'
