#!/bin/bash

# Open an org-capture popup frame from the shell. This opens a temporary emacs
# daemon if emacs isn't already running.
#
# Usage: org-capture [-k KEY] [MESSAGE]
# Examples:
#   org-capture -k n "To the mind that is still, the whole universe surrenders."

set -e

# If emacs isn't running, we start a daemon
if ! emacsclient -s org --suppress-output --eval nil; then
  emacs --daemon=org
fi

# org-capture key mapped to argument flags
# keys=$(emacsclient -e "(+org-capture-available-keys)" | cut -d '"' -f2)
while getopts "hk:" opt; do
  key="\"$OPTARG\""
  break
done
shift $((OPTIND-1))

[ -t 0 ] && str="$*" || str=$(cat)

emacsclient -a "" \
  -s org \
  -c \
  -F '((name . "doom-capture") (width . 70) (height . 25) (transient . t) (display . ":0"))' \
  -e "(+org-capture/open-frame \"$str\" ${key:-nil})"
