# Catppuccin Latte for Kitty
# https://github.com/catppuccin/kitty

background            #eff1f5
foreground            #4c4f69
selection_background  #acb0be
selection_foreground  #4c4f69
cursor                #dc8a78
cursor_text_color     #eff1f5
url_color             #1e66f5

# Borders
active_border_color   #8839ef
inactive_border_color #9ca0b0
bell_border_color     #df8e1d

# Tabs
active_tab_background   #8839ef
active_tab_foreground   #eff1f5
inactive_tab_background #e6e9ef
inactive_tab_foreground #4c4f69
tab_bar_background      #dce0e8

# Normal colors
color0  #5c5f77
color1  #d20f39
color2  #40a02b
color3  #df8e1d
color4  #1e66f5
color5  #ea76cb
color6  #179299
color7  #acb0be

# Bright colors
color8  #6c6f85
color9  #d20f39
color10 #40a02b
color11 #df8e1d
color12 #1e66f5
color13 #ea76cb
color14 #179299
color15 #bcc0cc
