#!/usr/local/opt/ruby/bin/ruby

require 'json'

# query current focused desktop
windows_on_desktop = JSON.parse(`yabai -m query --windows --space`) 

for win in windows_on_desktop
  `yabai -m window #{win["id"]} --close`
end

`yabai -m space --focus prev`

`yabai -m space recent --destroy`


