

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources


#map capslock key to escape
xmodmap -e 'clear Lock'
xmodmap -e 'keycode 0x42 = Escape'

#bind unbound keys (such as media/volume keys) with xbindkeys
xbindkeys


#screen powersave
xset +dpms
xset dpms 0 0 300
exec awesome



#touchpad configuration
synclient HorizTwoFingerScroll=1
synclient CoastingFriction=40
synclient PalmDetect=1


#restart dropbox so we can see the icon in the system tray
systemctl restart dropbox@jeff
