;;; extras/lang/python.el -*- lexical-binding: t; -*-


(after! dap-mode
  (dap-register-debug-provider
   "debugpy"
   (lambda (conf)

     (plist-put conf :host "127.0.0.1")
     (plist-put conf :debugServer 5678)

     conf)
   )

  (dap-register-debug-template
   "debugpy in docker"
   ;(json-serialize
   (list :type "debugpy"
         :request "attach"
         :mode "remote"
         :pathMappings  [(
                          (localRoot . "/Users/Jeff.Parsons/workspaces/dreambox/Vault-Secrets-Engines/jobmaster")
                          (remoteRoot . "/jobmaster")
                          )]
         )
   ;)

    )

)

  ;; Compare debug templates to launch.json generated by VScode
  ;; also reference https://code.visualstudio.com/docs/editor/debugging#_launch-configurations

