# -*- mode:ruby -*-

tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "mas-cli/tap"
brew "mas"

# cli dev tools
brew "coreutils" # replace OSX utils with GNU stuff
brew "git"
brew "ripgrep"
brew "trash"
brew "markdown"
brew "the_platinum_searcher"

# spacemacs support
brew "gnupg2"

# Util Apps
mas "1Password", id: 1333542190
cask "dropbox"

## productivity apps
cask "rescuetime"

mas "Fantastical 2", id: 975937182
mas "Slack", id: 803453959

## OSX-augmentation apps
cask "bartender"
cask "istat-menus"
cask "zazu"
tap "koekeishiya/formulae"
brew "chunkwm"
brew "skhd"

## common apps/tools used in development
cask "docker"
cask "virtualbox"
cask "vagrant"
brew "awscli"


