# -*- mode:ruby -*-

###############################################################################
# setup hombrew core
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "mas-cli/tap"
brew "mas"

tap "parsoj/formulae" 

###############################################################################
# Apps

# Util Apps
mas "1Password", id: 1333542190
#cask "dropbox"
cask "expressvpn"

# Chat apps
cask "discord"
mas "Slack", id: 803453959
cask "zoom"

# productivity apps
mas "Things 3", id: 904280696
mas "Fantastical 2", id: 975937182
mas "PDF Expert", id: 1055273043
cask "freedom"

cask "brave-browser"

###############################################################################
# Development Apps
cask "docker"

mas "Xcode", id: 497799835

brew "plantuml"

###############################################################################
# Development cli tools

# cli dev tools
brew "coreutils" # replace OSX utils with GNU stuff
brew "git"
brew "git-lfs"
brew "ripgrep"
brew "trash"
brew "markdown"
brew "the_platinum_searcher"
brew "aspell"
brew "gnupg2"
brew "wget"
brew "fd"
brew "gnu-tar"
brew "sqlite"
#cask "mactex"
brew "gnutls"
brew "libressl"
brew "ruby"
brew "python" # several emacs packages require python packages to support them
brew "go"
brew "jq"
brew "protobuf"

# external devtools
brew "awscli"

################################################################################
# emacs 

#compiling emacs
brew "automake"
brew "pkg-config"
brew "texinfo"
brew "libxml2"
brew "gnutls"
brew "gtk+3"

tap "d12frosted/emacs-plus"
brew "d12frosted/emacs-plus/emacs-plus", args: ["with-modern-icon", "with-no-frame-refocus", "without-spacemacs-icon"]

################################################################################
# Menu Bar stuff
cask "istat-menus"
cask "bitbar"
cask "bartender"


################################################################################
#  skhd and yabai
tap "koekeishiya/formulae"
brew "skhd"
brew "yabai"


################################################################################
# Alfred

