#+TITLE: OSX config files
configurations for an OSX system.

- I tend to prefer code-only configuration tools like yabai or skhd over UI-heavy ones like Alfred or Keyboard-maestro,
  since I find the former much simpler and easier to manage if its just a single
  config file checked in to source control.
- for similar reasons, I tend to prefer simple bash scripts or apple scripts for
  automation over frameworks like Hammerspoon or the like, since there are fewer moving parts involved, they are more
  flexible, and they are easier to manage through source control.

** Bootstrapping
- I try to keep track of my important Brew installs through my Brewfile, so that
  I can bootstrap a new system quickly if I need to.
** Window Mangement
- I use [[https://github.com/koekeishiya/yabai][yabai]] for window management/tiling.
** Hotkeys
- all my keyboard shortcuts are managed by [[https://github.com/koekeishiya/skhd][skhd]] - a hotkey daemon for mac
- most of my hotkeys are bound either to calls to yabai's chunkc for window management,
  or to bash or apple scripts (located in the /scripts directory) that automate
  common desktop actions
** Menu Bar
- I use Bartenter to organize and hide menu bar items
*** in the menu bar
- iStat-Menus for pretty system health graphs
- [[https://github.com/matryer/bitbar][bitbar]] & some bash scripts for any random information that I want to display in the menu-bar
