#!/bin/zsh



################################################################################
# OSX scripts

export PATH="$HOME/.config/osx/scripts/:$PATH"

################################################################################
# swift

export SOURCEKIT_TOOLCHAIN_PATH="/Library/Developer/Toolchains/swift-latest.xctoolchain/"

################################################################################
# go

export CPATH="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/"
export CGO_ENABLED=1
export CC=gcc;


#export GOROOT="$(brew --prefix golang)/libexec"
#export GOPATH="$HOME/.go"
#export PATH="$PATH:$GOPATH/bin:$GOROOT/bin"
#export PATH="$PATH:$HOME/go/bin"

export GO111MODULE=on

export GOPATH=~/go/
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin


################################################################################
# ruby

export PATH="/usr/local/opt/ruby/bin:$PATH"
#export LDFLAGS="-L/usr/local/opt/ruby/lib"
#export CPPFLAGS="-I/usr/local/opt/ruby/include"
#export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"

################################################################################
# Python

export PATH="/usr/local/opt/python/libexec/bin:$PATH"
#alias python=/usr/local/bin/python3
export PATH="$HOME/.poetry/bin:$PATH"

################################################################################
# Terraform

alias tf=terraform

################################################################################
# required when compiling emacs
export PATH="/usr/local/opt/texinfo/bin:$PATH"
export LIBXML2_CFLAGS=`xml2-config --cflags`
export LIBXML2_LIBS=`xml2-config --libs`

export PATH=$PATH:/usr/local/Cellar/gnutls/3.6.10/bin/

################################################################################
# Calibre Config

export CALIBRE_CONFIG_DIRECTORY="~/Dropbox/AppData/Calibre/Config"

################################################################################
# init completions

fpath+=~/.config/zsh/zfunc/_poetry

autoload -U compinit
compinit


##########################################################################################
# AWS configurations
export AWS_PROFILE=legacy_tools

#export VAULT_TOKEN=$(curl https://vault.sandbox.glympse.com/v1/auth/github/login -d '{ "token": "'d388e298ea0c46e2808cff0578e2b2da60bd9b13'" }' | jq '.auth.client_token')

##########################################################################################
# Helper scripts

#source /Users/jeff/.config/osx/app_settings/bitbar/helpers/*
