#!/bin/zsh

################################################################################
# Homebrew

export HOMEBREW_NO_ANALYTICS=1
export PATH="/usr/local/opt/bin:$PATH"

################################################################################
# Emacs Support 
export PATH="/Applications/Emacs-NS.app/Contents/MacOS:$PATH"
export EDITOR="$HOME/dotfiles/osx/scripts/emacs/client"
export VISUAL="$EDITOR -c"

################################################################################
# OSX scripts

export PATH="$HOME/.config/osx/scripts/:$PATH"

################################################################################
# swift

export SOURCEKIT_TOOLCHAIN_PATH="/Library/Developer/Toolchains/swift-latest.xctoolchain/"

################################################################################
# go

export CPATH="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/"
export CGO_ENABLED=1
export CC=gcc;


#export GOROOT="$(brew --prefix golang)/libexec"
#export GOPATH="$HOME/.go"
#export PATH="$PATH:$GOPATH/bin:$GOROOT/bin"
export PATH="$PATH:go/bin"
export GO111MODULE=on

################################################################################
# ruby

export PATH="/usr/local/opt/ruby/bin:$PATH"
#export LDFLAGS="-L/usr/local/opt/ruby/lib"
#export CPPFLAGS="-I/usr/local/opt/ruby/include"
#export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"

################################################################################
# Python

export PATH="/usr/local/opt/python@3.8/bin:$PATH"
alias python=/usr/local/bin/python3
export PATH="$HOME/.poetry/bin:$PATH"

################################################################################
# Terraform

alias tf=terraform

################################################################################
# required when compiling emacs
export PATH="/usr/local/opt/texinfo/bin:$PATH"
export LIBXML2_CFLAGS=`xml2-config --cflags`
export LIBXML2_LIBS=`xml2-config --libs`

export PATH=$PATH:/usr/local/Cellar/gnutls/3.6.10/bin/

################################################################################
# Calibre Config

export CALIBRE_CONFIG_DIRECTORY="~/Dropbox/AppData/Calibre/Config"

################################################################################
# init completions

fpath+=~/.config/zsh/zfunc/_poetry

autoload -U compinit
compinit
