#!/bin/bash

# Combine macOS apps and Fish functions into a single fuzzy finder
{
    # List macOS apps with "APP:" prefix
    { find /Applications -maxdepth 1 -name "*.app"; find /System/Applications -maxdepth 1 -name "*.app"; } |
    awk -F'/' '{print "APP:" $0 " ## " substr($NF, 1, length($NF)-4)}'

    # List Fish functions with "FUNC:" prefix
    fish -c 'functions' | awk '{print "FUNC:" $0 " ## " $0}'
} |
fzf --delimiter ' ## ' --with-nth=2 --prompt='Launch > ' |
awk -F' ## ' '{print $1}' |
while read -r selection; do
    type="${selection%%:*}"
    value="${selection#*:}"

    if [ "$type" = "APP" ]; then
        open "$value"
    elif [ "$type" = "FUNC" ]; then
        fish -c "$value"
    fi
done
