#!/bin/bash 

{ find /Applications -maxdepth 1 -name "*.app"; find /System/Applications -maxdepth 1 -name "*.app"; } |
awk -F'/' '{print $0 " ## " $NF}' |
sed 's/\.app ## /\.app ## /' |
fzf --delimiter ' ## ' --with-nth=2 |
awk -F' ## ' '{print $1}' |
xargs open


  
  
  
  
  